Simplify local image builds
osism/node-image pull request #75
Opened 2023-11-14 16:49 UTC by scoopex

2023-11-15 08:55 UTC, berendt commented
Can you rename `create_image_flavour.sh` to `create-image-flavor.sh`. We have "OpenStack flavors" and I prefer to use `-` in filenames.

2023-11-15 10:02 UTC, scoopex commented
> Can you rename `create_image_flavour.sh` to `create-image-flavor.sh`. We have "OpenStack flavors" and I prefer to use `-` in filenames.

Of cou(!)rse :-)

2023-11-17 17:56 UTC, berendt commented
@scoopex Please rebase. Looks like this PR included the https://github.com/osism/node-image/commit/8a0fab5d98b1b698b90adf4c743f866564d84e0f.

2023-11-17 18:26 UTC, scoopex commented
> @scoopex Please rebase. Looks like this PR included the [8a0fab5](https://github.com/osism/node-image/commit/8a0fab5d98b1b698b90adf4c743f866564d84e0f).

Done :-)

2023-11-17 21:18 UTC, berendt requested changes

2023-11-17 21:18 UTC, berendt commented on create_image_flavour.sh
> +#!/bin/bash
This file should be removed.

2023-11-17 21:18 UTC, berendt commented on playbooks/build.yml
> +          ./create_image_flavour.sh {{ name }}
create-image-flavor.sh

2023-11-18 09:48 UTC, scoopex commented on create_image_flavour.sh
> +#!/bin/bash
Damn and done :-)

2023-11-18 09:48 UTC, scoopex commented on playbooks/build.yml
> +          ./create_image_flavour.sh {{ name }}
Damn and done :-)

2023-12-11 16:04 UTC, merged